#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================

name: Openwrt-AutoBuild

on: 
  # push: 
  #   branches:
  #     - master
  schedule:
    - cron: 0 16 */4 * *
  watch:
    types: started

env:
  REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
  PPPOE_USERNAME: ${{ secrets.PPPOE_USERNAME }}
  PPPOE_PASSWD: ${{ secrets.PPPOE_PASSWD }}
  SCKEY: ${{ secrets.SCKEY }}
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
  TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
  TZ: Asia/Shanghai

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    
    name: Build ${{matrix.target}}
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64,k2p,r2s]
        
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Load Settings.ini
      run: |
        source "${GITHUB_WORKSPACE}/common/settings.ini"
        echo "::set-env name=REPO_URL::${REPO_URL}"
        echo "::set-env name=REPO_BRANCH::${REPO_BRANCH}"
        echo "::set-env name=CONFIG_FILE::${CONFIG_FILE}"
        echo "::set-env name=DIY_SH::${DIY_SH}"
        echo "::set-env name=FREE_UP_DISK::${FREE_UP_DISK}"
        echo "::set-env name=SSH_ACTIONS::${SSH_ACTIONS}"
        echo "::set-env name=UPLOAD_BIN_DIR_FOR_ARTIFACT::${UPLOAD_BIN_DIR_FOR_ARTIFACT}"
        echo "::set-env name=UPLOAD_FIRMWARE_FOR_ARTIFACT::${UPLOAD_FIRMWARE_FOR_ARTIFACT}"
        echo "::set-env name=UPLOAD_FIRMWARE_FOR_RELEASE::${UPLOAD_FIRMWARE_FOR_RELEASE}"
        echo "::set-env name=UPLOAD_FIRMWARE_TO_COWTRANSFER::${UPLOAD_FIRMWARE_TO_COWTRANSFER}"
        echo "::set-env name=UPLOAD_FIRMWARE_TO_WETRANSFER::${UPLOAD_FIRMWARE_TO_WETRANSFER}"
        if [ ${{matrix.target}} == "k2p" ]; then
        echo "::set-env name=MTARGET::mipsel"
        elif [ ${{matrix.target}} == "x86_64" ]; then
        echo "::set-env name=MTARGET::x64"
        else
        echo "::set-env name=MTARGET::aarch64"
        fi

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler ccache xsltproc rename antlr3 gperf wget swig rsync sshpass
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
    
    - name: Get current date
      id: date
      run: |
        echo "::set-env name=date::$(date +'%m/%d_%Y_%H/%M')"
        echo "::set-env name=date2::$(date +'%m/%d %Y')"
        echo "::set-env name=date3::$(date +'%m.%d')"

    - name: Clone source code
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
        git clone https://github.com/garypang13/Actions-OpenWrt
      
    - name: Free up disk space
      if: env.FREE_UP_DISK == 'true'
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo mkdir -p -m 777 /mnt/openwrt/dl /mnt/openwrt/staging_dir
        #ln -s /mnt/openwrt/build_dir/hostpkg openwrt/build_dir/
        #ln -s /mnt/openwrt/build_dir/host openwrt/build_dir/
        ln -s /mnt/openwrt/dl openwrt/
        ln -s /mnt/openwrt/staging_dir openwrt/

    - name: Load custom configuration
      run: |
        cp -Rf Actions-OpenWrt/* openwrt/
        cp -Rf `find ./ -maxdepth 1 -type d ! -path './openwrt' ! -path './'` openwrt
        cd openwrt
        echo "Apply files..."
        if [ -f "common/feeds.conf" ]; then
        (
          mv common/feeds.conf ./
        )
        fi
        if [ -f "${{matrix.target}}/feeds.conf" ]; then
        (
          mv ${{matrix.target}}/feeds.conf ./
        )
        fi
        if [ -n "$(ls -A "common/files" 2>/dev/null)" ]; then
         cp -rf common/files files
        fi
        if [ -n "$(ls -A "${{matrix.target}}/files" 2>/dev/null)" ]; then
         cp -rf ${{matrix.target}}/files/* files/
        fi
        if [ -f "common/$DIY_SH" ]; then
        (
          chmod +x common/$DIY_SH
          /bin/bash "common/$DIY_SH"
        )
        fi       
        if [ -f "${{matrix.target}}/$DIY_SH" ]; then
        (
          chmod +x ${{matrix.target}}/$DIY_SH
          /bin/bash "${{matrix.target}}/$DIY_SH"
        )
        fi
         mv ${{matrix.target}}/$CONFIG_FILE .config
        if [ -f "common/default-settings" ]; then
         cp -f common/default-settings package/*/*/default-settings/files/zzz-default-settings
        fi
        if [ -f "${{matrix.target}}/default-settings" ]; then
         cat ${{matrix.target}}/default-settings >> package/*/*/default-settings/files/zzz-default-settings
        fi
        if [ -n "$(ls -A "common/diy" 2>/dev/null)" ]; then
         cp -Rf common/diy/* ./
        fi
        if [ -n "$(ls -A "${{matrix.target}}/diy" 2>/dev/null)" ]; then
         cp -Rf ${{matrix.target}}/diy/* ./
        fi
        if [ -n "$(ls -A "common/patches" 2>/dev/null)" ]; then
        (
          find "common/patches" -type f -name '*.patch' -print0 | sort -z | xargs -I % -t -0 -n 1 sh -c "cat '%'  | patch -d './' -p0 --forward" || true
        )
        fi
        if [ -n "$(ls -A "${{matrix.target}}/patches" 2>/dev/null)" ]; then
        (
          find "${{matrix.target}}/patches" -type f -name '*.patch' -print0 | sort -z | xargs -I % -t -0 -n 1 sh -c "cat '%'  | patch -d './' -p0 --forward" || true
        )
        fi
        make defconfig
        [ $(grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/') == generic ] && DEVICE_NAME=$(grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/CONFIG_TARGET_(.*)_DEVICE_.*=y/\1/') || DEVICE_NAME=$(grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/')
        DEVICE_NAME=`echo ${DEVICE_NAME/xiaomi_redmi-router/redmi}`
        echo "::set-env name=DEVICE_NAME::$DEVICE_NAME"
        
    - name: Default PPPOE Setting
      if: env.PPPOE_USERNAME && env.PPPOE_PASSWD
      run: |
        sed -i '$i uci set network.wan.username=${{ env.PPPOE_USERNAME }}' openwrt/package/*/*/default-settings/files/zzz-default-settings
        sed -i '$i uci set network.wan.password=${{ env.PPPOE_PASSWD }}' openwrt/package/*/*/default-settings/files/zzz-default-settings
        sed -i '$i uci commit network' openwrt/package/*/*/default-settings/files/zzz-default-settings
              
    - name: SSH connection to Actions
      uses: garypang13/debugger-action@master
      if: env.SSH_ACTIONS == 'true'

    - name: Download package
      id: package
      run: |
        cd openwrt
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Compile the firmware
      run: |
        cd openwrt
        echo -e "$(($(nproc)+1)) thread compile"
        make -j$(($(nproc)+1)) || make -j1 V=s
        echo "::set-env name=status::success"

    - name: Organize files
      id: organize
      run: |
        mkdir packages && cp -Rf `find openwrt/bin/packages/*/custom/ -type f` packages/
        cp openwrt/.config  packages/${{matrix.target}}_packages.config
        cp -Rf common/addons/* packages/
        if [ -n "$(ls -A "${{matrix.target}}/addons" 2>/dev/null)" ]; then
         cp -Rf ${{matrix.target}}/addons/* packages/
        fi
        bash common/opkg
        echo "::set-env name=FIRMWARE::$PWD/packages"
        Emoji=("ğŸ‰" "ğŸ¤" "âœ¨" "ğŸ" "ğŸˆ" "ğŸ„" "ğŸ¨" "ğŸ’‹" "ğŸ“" "ğŸ•" "ğŸ‰" "ğŸ’" "ğŸŒ´" "ğŸš€" "ğŸ›¸" "ğŸ—½" "â›…" "ğŸŒˆ" "ğŸ”¥" "â›„" "ğŸ¶" "ğŸ…" "ğŸ¦„" "ğŸ¤")
        RANDOM=$$$(date +%s)
        rand=$[$RANDOM % ${#Emoji[@]}]
        echo "::set-env name=EMOJI::${Emoji[$rand]}"

    - name: Upload firmware to cowtransfer
      if: env.UPLOAD_FIRMWARE_TO_COWTRANSFER == 'true'
      continue-on-error: true
      run: |
        curl -fsSL git.io/file-transfer | sh
        cowurl=$(./transfer cow --block 2621440 -s --no-progress ${FIRMWARE})
        cowurl=$(echo $cowurl | grep -o -E "https[^ ]*")
        echo "::set-env name=COWURL::$cowurl"
        echo "Download Link: ${{ env.EMOJI }} $cowurl ${{ env.EMOJI }} ğŸš€"
 
    - name: Upload firmware to WeTransfer
      if: env.UPLOAD_FIRMWARE_TO_WETRANSFER == 'true'
      continue-on-error: true
      run: |
        curl -fsSL git.io/file-transfer | sh
        wetrans=$(./transfer wet -s -p 16 --no-progress ${FIRMWARE})
        wetrans=$(echo $wetrans | grep -o -E "https[^ ]*")
        echo "::set-env name=WETRANS::$wetrans"
        echo "Download Link: ${{ env.EMOJI }} $wetrans ${{ env.EMOJI }} ğŸš€"

    - name: Create release
      id: create_release
      uses: actions/create-release@main
      continue-on-error: true
      if: env.REPO_TOKEN && env.UPLOAD_FIRMWARE_FOR_RELEASE == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
      with:
        tag_name: ${{ env.date }}_${{ env.MTARGET }}
        release_name: ${{ env.date2 }} ${{ env.MTARGET }} Packages ${{ env.EMOJI }}
        body: |
            å¢™å†…åŠ é€Ÿä¸‹è½½ğŸ”¥:
            
            å¥¶ç‰›å¿«ä¼ : ${{ env.COWURL }} ğŸš€
            
            WeTransfer: ${{ env.WETRANS }} ${{ env.EMOJI }}
            
            ${{ env.NOTICE }}
        draft: false
        prerelease: false

    - name: Upload packages for release
      uses: csexton/release-asset-action@master
      continue-on-error: true
      if: env.REPO_TOKEN && env.UPLOAD_FIRMWARE_FOR_RELEASE == 'true'
      with:
        pattern: "${{ env.FIRMWARE }}/*"
        github-token: ${{ secrets.REPO_TOKEN }}
        release-url: ${{ steps.create_release.outputs.upload_url }}
 
    - name: deploy files to server
      uses: easingthemes/ssh-deploy@master
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-avzr --delete"
        SOURCE: "packages/"
        REMOTE_HOST: op.supes.top
        REMOTE_USER: root
        TARGET: "/www/wwwroot/op.supes.top/packages/${{ env.MTARGET }}/"

    - name: Upload packages for artifact
      uses: actions/upload-artifact@main
      continue-on-error: true
      if: env.UPLOAD_FIRMWARE_FOR_ARTIFACT == 'true'
      with:
        name: ${{ env.date3 }} ${{ env.MTARGET }}
        path: ${{ env.FIRMWARE }}

    - name: WeChat notification
      if: env.SCKEY
      run: |
        [ ${{ env.status }} == 'success' ] && curl https://sc.ftqq.com/${{ secrets.SCKEY }}.send?text=ğŸ‰OpenWrt_${{ env.date3 }}_${{ env.MTARGET }}è½¯ä»¶ä»“åº“å·²æ›´æ–°ğŸ˜‹|| curl https://sc.ftqq.com/${{ secrets.SCKEY }}.send?text=âŒOpenWrt_${{ env.date3 }}_${{ env.MTARGET }}è½¯ä»¶ä»“åº“æ›´æ–°å¤±è´¥ğŸ˜‚

    - name: Telegram notification
      if: env.TELEGRAM_TOKEN
      run: |
        # [ ${{ env.status }} == 'success' ] && curl -k --data chat_id="-1001382947163" --data "text=ğŸ‰ OpenWrt ${{ env.date3 }} ${{ env.MTARGET }} è½¯ä»¶ä»“åº“å·²æ›´æ–° ğŸ˜‹  ${{ env.COWURL }}   ${{ env.WETRANS }} ğŸš€" "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage"
